// words: en, ja, syl (syllables for stress), acc (accent position, 1-indexed)
// cloze: sentence, translation, answer (form in blank), wrong choices
// Single-syllable words have no syl/acc (skipped in stress mode)

export const sources = [
  {
    id: "source2",
    title: "B英単語ターゲット1900 小テスト①（301-350）",
    subtitle: "release, emerge, enable ...",
    words: [
      { en: "release", ja: "を放出する；を解放する；を発表する", syl: "re·lease", acc: 2 },
      { en: "emerge", ja: "現れる；明らかになる；台頭する", syl: "e·merge", acc: 2 },
      { en: "enable", ja: "（人）が…できるようにする；を可能にする", syl: "en·a·ble", acc: 2 },
      { en: "rely", ja: "頼る", syl: "re·ly", acc: 2 },
      { en: "adopt", ja: "を採用する；（態度など）をとる；を養子にする", syl: "a·dopt", acc: 2 },
      { en: "engage", ja: "を従事させる；を雇う；従事する", syl: "en·gage", acc: 2 },
      { en: "expand", ja: "（を）拡大する；（を）詳説する", syl: "ex·pand", acc: 2 },
      { en: "preserve", ja: "を保存する；を保持する；を保護する", syl: "pre·serve", acc: 2 },
      { en: "destroy", ja: "を破壊する；（人）を破滅させる", syl: "de·stroy", acc: 2 },
      { en: "evolve", ja: "（徐々に）発展する；進化する", syl: "e·volve", acc: 2 },
      { en: "warn", ja: "（人）に警告［注意］する" },
      { en: "surround", ja: "を取り巻く；にまつわる", syl: "sur·round", acc: 2 },
      { en: "element", ja: "要素，成分；元素", syl: "el·e·ment", acc: 1 },
      { en: "origin", ja: "起源；源", syl: "or·i·gin", acc: 1 },
      { en: "circumstance", ja: "状況，事情；境遇", syl: "cir·cum·stance", acc: 1 },
      { en: "select", ja: "を選ぶ", syl: "se·lect", acc: 2 },
      { en: "divide", ja: "を分ける", syl: "di·vide", acc: 2 },
      { en: "repeat", ja: "（を）繰り返す", syl: "re·peat", acc: 2 },
      { en: "flow", ja: "流れる" },
      { en: "consume", ja: "を消費する", syl: "con·sume", acc: 2 },
      { en: "organize", ja: "を準備する", syl: "or·ga·nize", acc: 1 },
      { en: "confuse", ja: "を混同する", syl: "con·fuse", acc: 2 },
      { en: "address", ja: "（問題など）に対処する", syl: "ad·dress", acc: 2 },
      { en: "bore", ja: "（人）を退屈させる" },
      { en: "participate", ja: "参加する", syl: "par·tic·i·pate", acc: 2 },
      { en: "phenomenon", ja: "現象", syl: "phe·nom·e·non", acc: 2 },
      { en: "host", ja: "を主催する" },
      { en: "target", ja: "（到達・攻撃）目標", syl: "tar·get", acc: 1 },
      { en: "appreciate", ja: "を正当に評価する", syl: "ap·pre·ci·ate", acc: 2 },
      { en: "profit", ja: "利益", syl: "prof·it", acc: 1 },
      { en: "vary", ja: "異なる；変わる", syl: "var·y", acc: 1 },
      { en: "operate", ja: "操作する；手術する", syl: "op·er·ate", acc: 1 },
      { en: "combine", ja: "を結合する", syl: "com·bine", acc: 2 },
      { en: "capacity", ja: "能力；容量", syl: "ca·pac·i·ty", acc: 2 },
      { en: "personality", ja: "個性；性格", syl: "per·son·al·i·ty", acc: 3 },
      { en: "predict", ja: "予測する", syl: "pre·dict", acc: 2 },
      { en: "stick", ja: "はまる；行き詰まる" },
      { en: "examine", ja: "を検査する；を調べる", syl: "ex·am·ine", acc: 2 },
      { en: "trust", ja: "を信じる；を信頼する" },
      { en: "judge", ja: "を判断する" },
      { en: "acquire", ja: "を習得する；を獲得する", syl: "ac·quire", acc: 2 },
      { en: "shift", ja: "を移す；移る" },
      { en: "atmosphere", ja: "大気；雰囲気", syl: "at·mos·phere", acc: 1 },
      { en: "refuse", ja: "を拒否する；を断る", syl: "re·fuse", acc: 2 },
      { en: "convince", ja: "を納得させる", syl: "con·vince", acc: 2 },
      { en: "strike", ja: "感銘を与える；打つ" },
      { en: "complain", ja: "不満を言う", syl: "com·plain", acc: 2 },
      { en: "recall", ja: "を思い出す", syl: "re·call", acc: 2 },
      { en: "principle", ja: "原則；原理", syl: "prin·ci·ple", acc: 1 },
      { en: "extend", ja: "を延長する；を拡張する", syl: "ex·tend", acc: 2 },
    ],
    cloze: [
      { en: "release", sentence: "The government decided to (   ) the prisoner.", translation: "政府はその囚人を解放することにした。", answer: "release", wrong: ["represent", "remove", "require"] },
      { en: "emerge", sentence: "New leaders (   ) during times of crisis.", translation: "危機の時代に新しいリーダーが現れる。", answer: "emerge", wrong: ["occur", "examine", "represent"] },
      { en: "enable", sentence: "Technology can (   ) people to work from home.", translation: "テクノロジーは人々が在宅勤務できるようにする。", answer: "enable", wrong: ["examine", "estimate", "emerge"] },
      { en: "rely", sentence: "Children (   ) on their parents for support.", translation: "子供は支援のために親に頼る。", answer: "rely", wrong: ["reflect", "relax", "respond"] },
      { en: "adopt", sentence: "The company plans to (   ) a new policy.", translation: "その会社は新しい方針を採用する予定だ。", answer: "adopt", wrong: ["admit", "ignore", "attract"] },
      { en: "engage", sentence: "Schools should (   ) students in creative activities.", translation: "学校は生徒を創造的な活動に従事させるべきだ。", answer: "engage", wrong: ["examine", "encourage", "earn"] },
      { en: "expand", sentence: "The business wants to (   ) into new markets.", translation: "その事業は新しい市場に拡大したい。", answer: "expand", wrong: ["exist", "admit", "control"] },
      { en: "preserve", sentence: "We must (   ) the natural environment.", translation: "自然環境を保存しなければならない。", answer: "preserve", wrong: ["promote", "prefer", "prevent"] },
      { en: "destroy", sentence: "The earthquake could (   ) entire cities.", translation: "その地震は都市全体を破壊する可能性がある。", answer: "destroy", wrong: ["define", "determine", "describe"] },
      { en: "evolve", sentence: "Languages (   ) over time.", translation: "言語は時間とともに進化する。", answer: "evolve", wrong: ["exist", "increase", "emerge"] },
      { en: "warn", sentence: "The sign (   ) drivers of the sharp curve.", translation: "その標識はドライバーに急カーブを警告する。", answer: "warns", wrong: ["inspires", "mentions", "amazes"] },
      { en: "surround", sentence: "Mountains (   ) the small village.", translation: "山がその小さな村を取り巻いている。", answer: "surround", wrong: ["survey", "supply", "release"] },
      { en: "element", sentence: "Water is an essential (   ) of life.", translation: "水は生命の不可欠な要素だ。", answer: "element", wrong: ["cell", "source", "environment"] },
      { en: "origin", sentence: "Scientists study the (   ) of the universe.", translation: "科学者たちは宇宙の起源を研究する。", answer: "origin", wrong: ["track", "focus", "cell"] },
      { en: "circumstance", sentence: "Under no (   ) should you open this door.", translation: "いかなる状況でもこのドアを開けてはならない。", answer: "circumstance", wrong: ["quality", "region", "surface"] },
      { en: "select", sentence: "Please (   ) the best answer.", translation: "最も適切な答えを選んでください。", answer: "select", wrong: ["solve", "spread", "propose"] },
      { en: "divide", sentence: "We need to (   ) the work equally.", translation: "仕事を均等に分ける必要がある。", answer: "divide", wrong: ["destroy", "desire", "doubt"] },
      { en: "repeat", sentence: "Could you (   ) that question please?", translation: "その質問を繰り返していただけますか？", answer: "repeat", wrong: ["compete", "prevent", "appeal"] },
      { en: "flow", sentence: "The river (   ) into the sea.", translation: "川は海に流れる。", answer: "flows", wrong: ["relies", "seeks", "occurs"] },
      { en: "consume", sentence: "Americans (   ) more energy than most countries.", translation: "アメリカ人はほとんどの国よりも多くのエネルギーを消費する。", answer: "consume", wrong: ["consider", "compare", "manage"] },
      { en: "organize", sentence: "We need to (   ) a welcome party for the new teacher.", translation: "新しい先生のために歓迎会を準備する必要がある。", answer: "organize", wrong: ["notice", "provide", "oppose"] },
      { en: "confuse", sentence: "The complicated instructions (   ) many people.", translation: "複雑な説明は多くの人を混同させる。", answer: "confuse", wrong: ["include", "connect", "conduct"] },
      { en: "address", sentence: "The mayor will (   ) the housing problem.", translation: "市長はその住宅問題に対処するだろう。", answer: "address", wrong: ["associate", "doubt", "assume"] },
      { en: "bore", sentence: "Long speeches often (   ) the audience.", translation: "長いスピーチはよく聴衆を退屈させる。", answer: "bore", wrong: ["dig", "bite", "starve"] },
      { en: "participate", sentence: "All students must (   ) in the school festival.", translation: "すべての生徒は学園祭に参加しなければならない。", answer: "participate", wrong: ["adapt", "rely", "contribute"] },
      { en: "phenomenon", sentence: "Global warming is a serious (   ).", translation: "地球温暖化は深刻な現象だ。", answer: "phenomenon", wrong: ["influence", "norm", "feature"] },
      { en: "host", sentence: "Japan will (   ) the next international conference.", translation: "日本が次の国際会議を主催する。", answer: "host", wrong: ["halt", "publish", "print"] },
      { en: "target", sentence: "The company set a sales (   ) for this quarter.", translation: "その会社は今四半期の売上目標を設定した。", answer: "target", wrong: ["fee", "trade", "right"] },
      { en: "appreciate", sentence: "I really (   ) your help.", translation: "あなたの助けを正当に評価しています。", answer: "appreciate", wrong: ["mention", "predict", "claim"] },
      { en: "profit", sentence: "The company made a large (   ) this year.", translation: "その会社は今年大きな利益を得た。", answer: "profit", wrong: ["value", "figure", "custom"] },
      { en: "vary", sentence: "Prices (   ) depending on the season.", translation: "価格は季節によって異なる。", answer: "vary", wrong: ["emerge", "occur", "decline"] },
      { en: "operate", sentence: "She learned how to (   ) the machine.", translation: "彼女はその機械を操作する方法を学んだ。", answer: "operate", wrong: ["organize", "observe", "overcome"] },
      { en: "combine", sentence: "You can (   ) the two ingredients together.", translation: "2つの材料を結合することができる。", answer: "combine", wrong: ["consume", "compare", "compete"] },
      { en: "capacity", sentence: "The stadium has a (   ) of 50,000.", translation: "そのスタジアムは5万人の容量がある。", answer: "capacity", wrong: ["ceremony", "category", "community"] },
      { en: "personality", sentence: "She has a very cheerful (   ).", translation: "彼女はとても明るい個性を持っている。", answer: "personality", wrong: ["principle", "resource", "circumstance"] },
      { en: "predict", sentence: "The professor (   ) that the economy would recover.", translation: "その教授は経済が回復すると予測した。", answer: "predicted", wrong: ["preserved", "ignored", "promoted"] },
      { en: "stick", sentence: "We were (   ) in a heavy traffic jam last night.", translation: "昨夜、ひどい交通渋滞にはまった。", answer: "stuck", wrong: ["stored", "sought", "spread"] },
      { en: "examine", sentence: "The doctor (   ) the patient's stomach with a medical device.", translation: "医者は医療機器で患者の胃を検査した。", answer: "examined", wrong: ["determined", "approached", "controlled"] },
      { en: "trust", sentence: "I have decided to ignore any advice from others and (   ) my judgment.", translation: "他人の助言を無視して自分の判断を信じることにした。", answer: "trust", wrong: ["respect", "prefer", "treat"] },
      { en: "judge", sentence: "We should not (   ) people by their appearance.", translation: "人を外見で判断すべきではない。", answer: "judge", wrong: ["insist", "admit", "control"] },
      { en: "acquire", sentence: "(   ) knowledge is one thing, but applying it is another.", translation: "知識を習得することと応用することは別物だ。", answer: "Acquiring", wrong: ["Dividing", "Desiring", "Purchasing"] },
      { en: "shift", sentence: "The company (   ) its manufacturing base to India.", translation: "その会社は製造拠点をインドに移した。", answer: "shifted", wrong: ["assisted", "removed", "carried"] },
      { en: "atmosphere", sentence: "Gasses like carbon dioxide increase the temperature in the (   ).", translation: "二酸化炭素のような気体が大気中の温度を上昇させる。", answer: "atmosphere", wrong: ["surface", "advantage", "region"] },
      { en: "refuse", sentence: "The journalist (   ) to answer the questions about the source of the information.", translation: "そのジャーナリストは情報源に関する質問に答えることを拒否した。", answer: "refused", wrong: ["prevented", "bore", "revealed"] },
      { en: "convince", sentence: "The doctor (   ) me that exercising would improve my health.", translation: "医者は運動が健康を改善すると私を納得させた。", answer: "convinced", wrong: ["compared", "completed", "consumed"] },
      { en: "strike", sentence: "Visitors to Florence are (   ) by its wonderful architecture and artwork.", translation: "フィレンツェを訪れる人々はその素晴らしい建築と芸術作品に感銘を受ける。", answer: "struck", wrong: ["mingled", "avoided", "stated"] },
      { en: "complain", sentence: "People often (   ) about the government's reaction to natural disasters.", translation: "人々は自然災害に対する政府の対応についてよく不満を言う。", answer: "complain", wrong: ["consider", "compare", "concern"] },
      { en: "recall", sentence: "Much as I tried, I could not (   ) her physical appearance.", translation: "いくら努力しても、彼女の容姿を思い出せなかった。", answer: "recall", wrong: ["release", "realize", "recognize"] },
      { en: "principle", sentence: "The (   ) of first-come-first-served is simple and fair.", translation: "先着順の原則はシンプルで公平だ。", answer: "principle", wrong: ["statement", "influence", "thought"] },
      { en: "extend", sentence: "Stores often (   ) their business hours for the convenience of customers.", translation: "店は顧客の利便性のために営業時間を延長することが多い。", answer: "extend", wrong: ["admit", "attract", "trust"] },
    ]
  },
  {
    id: "source3",
    title: "B英単語ターゲット1900 小テスト②（351-400）",
    subtitle: "fossil, overall, disaster ...",
    words: [
      { en: "fossil", ja: "化石；時代遅れの人［物］", syl: "fos·sil", acc: 1 },
      { en: "overall", ja: "総合的な；全体的な", syl: "o·ver·all", acc: 1 },
      { en: "disaster", ja: "災害；惨事", syl: "di·sas·ter", acc: 2 },
      { en: "web", ja: "（クモの）巣" },
      { en: "perspective", ja: "観点，見方；遠近法", syl: "per·spec·tive", acc: 2 },
      { en: "fund", ja: "基金，資金" },
      { en: "biological", ja: "生物学（上）の", syl: "bi·o·log·i·cal", acc: 3 },
      { en: "crisis", ja: "危機", syl: "cri·sis", acc: 1 },
      { en: "soil", ja: "土地，土壌；温床" },
      { en: "domestic", ja: "家庭の；国内の；飼いならされた", syl: "do·mes·tic", acc: 2 },
      { en: "custom", ja: "慣習；税関；関税", syl: "cus·tom", acc: 1 },
      { en: "psychology", ja: "心理学；心理（状態）", syl: "psy·chol·o·gy", acc: 2 },
      { en: "agriculture", ja: "農業；農学，畜産", syl: "ag·ri·cul·ture", acc: 1 },
      { en: "symbol", ja: "象徴；記号；標章", syl: "sym·bol", acc: 1 },
      { en: "nuclear", ja: "核の，原子力の", syl: "nu·cle·ar", acc: 1 },
      { en: "wealth", ja: "富" },
      { en: "firm", ja: "確固たる" },
      { en: "conscious", ja: "意識して", syl: "con·scious", acc: 1 },
      { en: "severe", ja: "厳しい", syl: "se·vere", acc: 2 },
      { en: "military", ja: "軍の", syl: "mil·i·tar·y", acc: 1 },
      { en: "resident", ja: "居住者", syl: "res·i·dent", acc: 1 },
      { en: "enormous", ja: "莫大な", syl: "e·nor·mous", acc: 2 },
      { en: "artificial", ja: "人工の", syl: "ar·ti·fi·cial", acc: 3 },
      { en: "version", ja: "版", syl: "ver·sion", acc: 1 },
      { en: "vocabulary", ja: "語彙", syl: "vo·cab·u·lar·y", acc: 2 },
      { en: "institution", ja: "機関", syl: "in·sti·tu·tion", acc: 3 },
      { en: "rural", ja: "田舎の", syl: "ru·ral", acc: 1 },
      { en: "mass", ja: "大規模な" },
      { en: "constant", ja: "絶え間ない", syl: "con·stant", acc: 1 },
      { en: "threat", ja: "脅威" },
      { en: "gender", ja: "性別", syl: "gen·der", acc: 1 },
      { en: "desert", ja: "砂漠", syl: "des·ert", acc: 1 },
      { en: "fundamental", ja: "基本的な", syl: "fun·da·men·tal", acc: 3 },
      { en: "analysis", ja: "分析", syl: "a·nal·y·sis", acc: 2 },
      { en: "intelligent", ja: "知能のある；聡明な", syl: "in·tel·li·gent", acc: 2 },
      { en: "overseas", ja: "海外で；海外の", syl: "o·ver·seas", acc: 3 },
      { en: "manners", ja: "礼儀", syl: "man·ners", acc: 1 },
      { en: "court", ja: "法廷；裁判所" },
      { en: "capable", ja: "能力がある", syl: "ca·pa·ble", acc: 1 },
      { en: "typical", ja: "典型的な", syl: "typ·i·cal", acc: 1 },
      { en: "accurate", ja: "正確な", syl: "ac·cu·rate", acc: 1 },
      { en: "authority", ja: "当局；権威", syl: "au·thor·i·ty", acc: 2 },
      { en: "document", ja: "文書", syl: "doc·u·ment", acc: 1 },
      { en: "nevertheless", ja: "それにもかかわらず", syl: "nev·er·the·less", acc: 4 },
      { en: "vote", ja: "投票" },
      { en: "visual", ja: "視覚の", syl: "vis·u·al", acc: 1 },
      { en: "lecture", ja: "講義", syl: "lec·ture", acc: 1 },
      { en: "sight", ja: "景色；名所" },
      { en: "campaign", ja: "運動", syl: "cam·paign", acc: 2 },
      { en: "convenient", ja: "便利な", syl: "con·ve·nient", acc: 2 },
    ],
    cloze: [
      { en: "fossil", sentence: "Scientists discovered a rare (   ) in the desert.", translation: "科学者たちは砂漠で珍しい化石を発見した。", answer: "fossil", wrong: ["species", "focus", "material"] },
      { en: "overall", sentence: "The (   ) quality of the product is excellent.", translation: "その製品の全体的な品質は優秀だ。", answer: "overall", wrong: ["essential", "sufficient", "aggressive"] },
      { en: "disaster", sentence: "The earthquake was a terrible (   ).", translation: "その地震はひどい災害だった。", answer: "disaster", wrong: ["struggle", "atmosphere", "threat"] },
      { en: "web", sentence: "A spider built a (   ) in the corner.", translation: "クモが隅に巣を作った。", answer: "web", wrong: ["crime", "comb", "vision"] },
      { en: "perspective", sentence: "Travel gives you a different (   ) on life.", translation: "旅行は人生に対して異なる観点を与える。", answer: "perspective", wrong: ["principle", "trend", "personality"] },
      { en: "fund", sentence: "The government created a special (   ) for education.", translation: "政府は教育のための特別な基金を設立した。", answer: "fund", wrong: ["function", "fault", "rent"] },
      { en: "biological", sentence: "He studies (   ) processes in the human body.", translation: "彼は人体の生物学的なプロセスを研究している。", answer: "biological", wrong: ["tropical", "financial", "political"] },
      { en: "crisis", sentence: "The country is facing an economic (   ).", translation: "その国は経済の危機に直面している。", answer: "crisis", wrong: ["cause", "situation", "content"] },
      { en: "soil", sentence: "Plants grow well in rich (   ).", translation: "植物は豊かな土壌でよく育つ。", answer: "soil", wrong: ["moisture", "coil", "toil"] },
      { en: "domestic", sentence: "(   ) flights are cheaper than international ones.", translation: "国内便は国際便より安い。", answer: "Domestic", wrong: ["Common", "Public", "Rural"] },
      { en: "custom", sentence: "It is a (   ) to bow when greeting in Japan.", translation: "日本では挨拶の際にお辞儀をするのが慣習だ。", answer: "custom", wrong: ["medium", "value", "region"] },
      { en: "psychology", sentence: "She is studying (   ) at university.", translation: "彼女は大学で心理学を学んでいる。", answer: "psychology", wrong: ["literature", "philosophy", "technology"] },
      { en: "agriculture", sentence: "(   ) is the main industry in this region.", translation: "この地域では農業が主要産業だ。", answer: "Agriculture", wrong: ["Manufacture", "Commerce", "Construction"] },
      { en: "symbol", sentence: "The dove is a (   ) of peace.", translation: "鳩は平和の象徴だ。", answer: "symbol", wrong: ["passion", "symmetry", "sign"] },
      { en: "nuclear", sentence: "Many countries debate (   ) energy policies.", translation: "多くの国が原子力エネルギー政策について議論する。", answer: "nuclear", wrong: ["particular", "genetic", "physical"] },
      { en: "wealth", sentence: "Hard work can lead to great (   ).", translation: "努力は大きな富につながる。", answer: "wealth", wrong: ["result", "income", "status"] },
      { en: "firm", sentence: "The manager was (   ) in her decision.", translation: "マネージャーは決断において確固たる態度だった。", answer: "firm", wrong: ["obvious", "moist", "gentle"] },
      { en: "conscious", sentence: "He was not (   ) of the danger around him.", translation: "彼は周囲の危険を意識していなかった。", answer: "conscious", wrong: ["obvious", "essential", "potential"] },
      { en: "severe", sentence: "The region suffered (   ) flooding last year.", translation: "その地域は昨年厳しい洪水に見舞われた。", answer: "severe", wrong: ["extreme", "rare", "exact"] },
      { en: "military", sentence: "The (   ) forces were deployed to the border.", translation: "軍の部隊が国境に配置された。", answer: "military", wrong: ["strict", "violent", "social"] },
      { en: "resident", sentence: "Each (   ) of the building received a notice.", translation: "そのビルの各居住者は通知を受け取った。", answer: "resident", wrong: ["personality", "colleague", "region"] },
      { en: "enormous", sentence: "The company made an (   ) profit.", translation: "その会社は莫大な利益を得た。", answer: "enormous", wrong: ["various", "overall", "primary"] },
      { en: "artificial", sentence: "The flowers on the table are (   ).", translation: "テーブルの花は人工のものだ。", answer: "artificial", wrong: ["official", "physical", "financial"] },
      { en: "version", sentence: "Please download the latest (   ) of the software.", translation: "ソフトウェアの最新版をダウンロードしてください。", answer: "version", wrong: ["tendency", "value", "characteristic"] },
      { en: "vocabulary", sentence: "Reading helps expand your (   ).", translation: "読書は語彙を広げるのに役立つ。", answer: "vocabulary", wrong: ["claim", "figure", "achievement"] },
      { en: "institution", sentence: "The university is a respected (   ).", translation: "その大学は尊敬される機関だ。", answer: "institution", wrong: ["function", "revolution", "colleague"] },
      { en: "rural", sentence: "Many young people move from (   ) areas to cities.", translation: "多くの若者が田舎の地域から都市に移る。", answer: "rural", wrong: ["native", "urban", "deserted"] },
      { en: "mass", sentence: "The event attracted (   ) media attention.", translation: "そのイベントは大規模なメディアの注目を集めた。", answer: "mass", wrong: ["stock", "audience", "tendency"] },
      { en: "constant", sentence: "The noise was a (   ) source of annoyance.", translation: "その騒音は絶え間ない苛立ちの原因だった。", answer: "constant", wrong: ["complex", "patient", "universal"] },
      { en: "threat", sentence: "Climate change is a serious (   ) to wildlife.", translation: "気候変動は野生生物にとって深刻な脅威だ。", answer: "threat", wrong: ["influence", "situation", "suffering"] },
      { en: "gender", sentence: "(   ) equality is an important social issue.", translation: "性別の平等は重要な社会問題だ。", answer: "Gender", wrong: ["Desert", "Analysis", "Version"] },
      { en: "desert", sentence: "The Sahara is the largest hot (   ) in the world.", translation: "サハラは世界最大の暑い砂漠だ。", answer: "desert", wrong: ["gender", "analysis", "border"] },
      { en: "fundamental", sentence: "Freedom of speech is a (   ) right.", translation: "言論の自由は基本的な権利だ。", answer: "fundamental", wrong: ["intelligent", "artificial", "enormous"] },
      { en: "analysis", sentence: "The scientist presented a detailed (   ) of the data.", translation: "科学者はデータの詳細な分析を提示した。", answer: "analysis", wrong: ["gender", "version", "institution"] },
      { en: "intelligent", sentence: "Dolphins are known to be very (   ) animals.", translation: "イルカは非常に聡明な動物として知られている。", answer: "intelligent", wrong: ["fundamental", "artificial", "enormous"] },
      { en: "overseas", sentence: "Japanese can travel (   ) easily because of the strong yen.", translation: "円高のおかげで日本人は簡単に海外旅行できる。", answer: "overseas", wrong: ["outdoors", "overall", "ahead"] },
      { en: "manners", sentence: "Smiling is part of good (   ).", translation: "笑顔はよいマナーの一部だ。", answer: "manners", wrong: ["causes", "ranges", "matters"] },
      { en: "court", sentence: "He confessed his crime in (   ).", translation: "彼は法廷で自分の罪を告白した。", answer: "court", wrong: ["context", "crop", "corporation"] },
      { en: "capable", sentence: "The brain is (   ) of processing information at high speed.", translation: "脳は高速で情報を処理する能力がある。", answer: "capable", wrong: ["actual", "proper", "independent"] },
      { en: "typical", sentence: "(   ) Hollywood movies feature car chases.", translation: "典型的なハリウッド映画はカーチェイスを特徴とする。", answer: "Typical", wrong: ["Ideal", "Current", "Common"] },
      { en: "accurate", sentence: "(   ) weather forecasts benefit farmers greatly.", translation: "正確な天気予報は農家に大きな利益をもたらす。", answer: "Accurate", wrong: ["Efficient", "Obvious", "Private"] },
      { en: "authority", sentence: "The government (   ) limited freedom of speech.", translation: "政府当局は言論の自由を制限した。", answer: "authorities", wrong: ["authors", "norms", "ancestors"] },
      { en: "document", sentence: "The library stores important (   ).", translation: "その図書館は重要な文書を保管している。", answer: "documents", wrong: ["bills", "literatures", "contents"] },
      { en: "nevertheless", sentence: "The watch is small; (   ), it is very useful.", translation: "その時計は小さいが、それにもかかわらず、とても役に立つ。", answer: "nevertheless", wrong: ["likewise", "furthermore", "therefore"] },
      { en: "vote", sentence: "Election results showed the percentage of (   ).", translation: "選挙結果は投票の割合を示した。", answer: "votes", wrong: ["views", "traits", "terms"] },
      { en: "visual", sentence: "The brain processes (   ) information from the eyes.", translation: "脳は目からの視覚情報を処理する。", answer: "visual", wrong: ["direct", "cognitive", "rural"] },
      { en: "lecture", sentence: "The professor gave an academic (   ).", translation: "その教授は学術的な講義を行った。", answer: "lecture", wrong: ["legend", "angle", "introduction"] },
      { en: "sight", sentence: "The island has beautiful natural (   ).", translation: "その島には美しい自然の景色がある。", answer: "sights", wrong: ["focuses", "wealth", "attitudes"] },
      { en: "campaign", sentence: "The recycling (   ) was a success.", translation: "そのリサイクルキャンペーンは成功した。", answer: "campaign", wrong: ["custom", "conflict", "consequence"] },
      { en: "convenient", sentence: "Online shopping is very (   ).", translation: "オンラインショッピングはとても便利だ。", answer: "convenient", wrong: ["mobile", "conscious", "patient"] },
    ]
  },
  {
    id: "source1",
    title: "B英単語ターゲット1900 小テスト③（401-450）",
    subtitle: "educate, amaze, appeal ...",
    words: [
      { en: "educate", ja: "を教育する；に教える；（能力など）を養う", syl: "ed·u·cate", acc: 1 },
      { en: "amaze", ja: "をびっくりさせる", syl: "a·maze", acc: 2 },
      { en: "appeal", ja: "訴える", syl: "ap·peal", acc: 2 },
      { en: "praise", ja: "を賞賛する；賛美する" },
      { en: "conclude", ja: "と結論づける；を締めくくる", syl: "con·clude", acc: 2 },
      { en: "handle", ja: "を処理する，扱う；を論じる", syl: "han·dle", acc: 1 },
      { en: "reject", ja: "を拒否する", syl: "re·ject", acc: 2 },
      { en: "expose", ja: "をさらす；を暴露する", syl: "ex·pose", acc: 2 },
      { en: "favor", ja: "に賛成する；を好む", syl: "fa·vor", acc: 1 },
      { en: "spell", ja: "語をつづる；という語になる" },
      { en: "consist", ja: "成る；ある", syl: "con·sist", acc: 2 },
      { en: "instruction", ja: "指示；製品の使用書", syl: "in·struc·tion", acc: 2 },
      { en: "religion", ja: "宗教；信条；信仰", syl: "re·li·gion", acc: 2 },
      { en: "breathe", ja: "呼吸する；を吸う" },
      { en: "comment", ja: "意見；批判", syl: "com·ment", acc: 1 },
      { en: "behave", ja: "振る舞う", syl: "be·have", acc: 2 },
      { en: "propose", ja: "を提案する", syl: "pro·pose", acc: 2 },
      { en: "purchase", ja: "を購入する", syl: "pur·chase", acc: 1 },
      { en: "explore", ja: "調査する", syl: "ex·plore", acc: 2 },
      { en: "tear", ja: "を引き裂く" },
      { en: "perceive", ja: "に気づく", syl: "per·ceive", acc: 2 },
      { en: "imply", ja: "を暗に意味する", syl: "im·ply", acc: 2 },
      { en: "intend", ja: "を意図する", syl: "in·tend", acc: 2 },
      { en: "repair", ja: "を修理する", syl: "re·pair", acc: 2 },
      { en: "inspire", ja: "奮起させる", syl: "in·spire", acc: 2 },
      { en: "rank", ja: "を位置づける" },
      { en: "harm", ja: "害" },
      { en: "category", ja: "部類", syl: "cat·e·go·ry", acc: 1 },
      { en: "instrument", ja: "器具", syl: "in·stru·ment", acc: 1 },
      { en: "confidence", ja: "自信", syl: "con·fi·dence", acc: 1 },
      { en: "settle", ja: "解決する；定住する", syl: "set·tle", acc: 1 },
      { en: "remind", ja: "に思い出させる", syl: "re·mind", acc: 2 },
      { en: "laboratory", ja: "実験室；研究所", syl: "lab·o·ra·to·ry", acc: 1 },
      { en: "insist", ja: "主張する；言い張る", syl: "in·sist", acc: 2 },
      { en: "neighborhood", ja: "近所；地域", syl: "neigh·bor·hood", acc: 1 },
      { en: "admit", ja: "認める；許可する", syl: "ad·mit", acc: 2 },
      { en: "generate", ja: "を生み出す；を発生させる", syl: "gen·er·ate", acc: 1 },
      { en: "recommend", ja: "を勧める；を推薦する", syl: "rec·om·mend", acc: 3 },
      { en: "demonstrate", ja: "を実証する；を示す", syl: "dem·on·strate", acc: 1 },
      { en: "presence", ja: "存在；出席", syl: "pres·ence", acc: 1 },
      { en: "advertise", ja: "を宣伝する；を広告する", syl: "ad·ver·tise", acc: 1 },
      { en: "aid", ja: "を援助する；を助ける" },
      { en: "bite", ja: "を噛む" },
      { en: "deliver", ja: "を配達する；を届ける", syl: "de·liv·er", acc: 2 },
      { en: "locate", ja: "を位置づける；の所在を見つける", syl: "lo·cate", acc: 2 },
    ],
    cloze: [
      { en: "educate", sentence: "We should (   ) children about the environment.", translation: "子供たちに環境について教育すべきだ。", answer: "educate", wrong: ["establish", "express", "estimate"] },
      { en: "amaze", sentence: "Her talent never fails to (   ) us.", translation: "彼女の才能はいつも私たちをびっくりさせる。", answer: "amaze", wrong: ["allow", "afford", "attract"] },
      { en: "appeal", sentence: "The charity will (   ) to the public for donations.", translation: "その慈善団体は寄付を求めて人々に訴える。", answer: "appeal", wrong: ["gain", "indicate", "approve"] },
      { en: "praise", sentence: "The coach always (   ) players who try their best.", translation: "コーチは全力を尽くす選手をいつも賞賛する。", answer: "praises", wrong: ["prepares", "preserves", "predicts"] },
      { en: "conclude", sentence: "We can (   ) that the plan was successful.", translation: "その計画は成功だったと結論づけられる。", answer: "conclude", wrong: ["estimate", "claim", "complain"] },
      { en: "handle", sentence: "She can (   ) any problem calmly.", translation: "彼女はどんな問題も冷静に処理できる。", answer: "handle", wrong: ["cure", "hide", "supply"] },
      { en: "reject", sentence: "The university may (   ) your application.", translation: "大学はあなたの出願を拒否するかもしれない。", answer: "reject", wrong: ["reserve", "release", "regard"] },
      { en: "expose", sentence: "The report will (   ) the company's illegal activities.", translation: "その報告書は会社の違法行為を暴露するだろう。", answer: "expose", wrong: ["earn", "expect", "examine"] },
      { en: "favor", sentence: "Most citizens (   ) the new policy.", translation: "ほとんどの市民は新しい政策に賛成している。", answer: "favor", wrong: ["notice", "force", "oppose"] },
      { en: "spell", sentence: "Please (   ) your name slowly.", translation: "ゆっくりお名前をつづってください。", answer: "spell", wrong: ["frighten", "bury", "remark"] },
      { en: "consist", sentence: "The committee (   ) of twelve members.", translation: "委員会は12名のメンバーで成る。", answer: "consists", wrong: ["credits", "produces", "adds"] },
      { en: "instruction", sentence: "Read the (   ) carefully before starting.", translation: "始める前に使用書をよく読んでください。", answer: "instructions", wrong: ["interests", "instruments", "institutions"] },
      { en: "religion", sentence: "(   ) has influenced art throughout history.", translation: "宗教は歴史を通じて芸術に影響を与えてきた。", answer: "Religion", wrong: ["Situation", "Region", "Function"] },
      { en: "breathe", sentence: "It is difficult to (   ) in polluted air.", translation: "汚れた空気の中では呼吸するのが難しい。", answer: "breathe", wrong: ["decrease", "decline", "behave"] },
      { en: "comment", sentence: "He made a short (   ) on the topic.", translation: "彼はそのテーマについて短い意見を述べた。", answer: "comment", wrong: ["tablet", "memory", "novel"] },
      { en: "behave", sentence: "She knows how to (   ) in a polite manner at a restaurant.", translation: "彼女はレストランで礼儀正しく振る舞う方法を知っている。", answer: "behave", wrong: ["decline", "depend", "contribute"] },
      { en: "propose", sentence: "She (   ) a new strategy to the team.", translation: "彼女はチームに新しい戦略を提案した。", answer: "proposed", wrong: ["rejected", "exposed", "evaluated"] },
      { en: "purchase", sentence: "I decided to (   ) the book online.", translation: "その本をオンラインで購入することにした。", answer: "purchase", wrong: ["respect", "request", "recommend"] },
      { en: "explore", sentence: "Researchers (   ) the unknown territory.", translation: "研究者たちは未知の領域を調査した。", answer: "explored", wrong: ["admitted", "evaluated", "earned"] },
      { en: "tear", sentence: "Do not (   ) the pages of the library book.", translation: "図書館の本のページを引き裂かないでください。", answer: "tear", wrong: ["maintain", "provide", "treat"] },
      { en: "perceive", sentence: "Few people (   ) the risk of the situation.", translation: "その状況の危険に気づく人はほとんどいなかった。", answer: "perceived", wrong: ["preserved", "performed", "prepared"] },
      { en: "imply", sentence: "Boy's body language (   ) he didn't want to go to school.", translation: "その少年のボディーランゲージは学校に行きたくないことを暗示していた。", answer: "implied", wrong: ["identified", "ignored", "imported"] },
      { en: "intend", sentence: "We (   ) to visit Paris next summer.", translation: "来年の夏にパリを訪れるつもりだ。", answer: "intend", wrong: ["include", "involve", "indicate"] },
      { en: "repair", sentence: "He hired someone to (   ) the broken window.", translation: "彼は壊れた窓を修理するために人を雇った。", answer: "repair", wrong: ["remove", "represent", "request"] },
      { en: "inspire", sentence: "The speech (   ) many young people to volunteer.", translation: "そのスピーチは多くの若者をボランティアに奮起させた。", answer: "inspired", wrong: ["intended", "identified", "ignored"] },
      { en: "rank", sentence: "Experts (   ) this school among the best.", translation: "専門家はこの学校を最高の一つに位置づけている。", answer: "rank", wrong: ["inform", "consider", "remove"] },
      { en: "harm", sentence: "Smoking can seriously (   ) your health.", translation: "喫煙は健康に深刻な害を与える可能性がある。", answer: "harm", wrong: ["handle", "struggle", "purpose"] },
      { en: "category", sentence: "This product falls into the food (   ).", translation: "この製品は食品の部類に入る。", answer: "category", wrong: ["exercise", "strategy", "technology"] },
      { en: "instrument", sentence: "This (   ) is used to measure temperature.", translation: "この器具は温度を測定するために使われる。", answer: "instrument", wrong: ["document", "organization", "substance"] },
      { en: "confidence", sentence: "Practice will build your (   ) for the exam.", translation: "練習が試験への自信を築くだろう。", answer: "confidence", wrong: ["evidence", "conflict", "influence"] },
      { en: "settle", sentence: "Should find lawyer to (   ) the legal problem.", translation: "その法的問題を解決するために弁護士を見つけるべきだ。", answer: "settle", wrong: ["seek", "suggest", "store"] },
      { en: "remind", sentence: "Please (   ) me of the meeting tomorrow.", translation: "明日の会議のことを思い出させてください。", answer: "remind", wrong: ["inspire", "mention", "amaze"] },
      { en: "laboratory", sentence: "Students conduct experiments in the (   ).", translation: "学生は実験室で実験を行う。", answer: "laboratory", wrong: ["instrument", "institution", "instruction"] },
      { en: "insist", sentence: "He (   ) on walking to school by himself.", translation: "彼は一人で歩いて通学することを主張した。", answer: "insisted", wrong: ["indicated", "improved", "identified"] },
      { en: "neighborhood", sentence: "Parents grew up in poor (   ).", translation: "両親は貧しい地域で育った。", answer: "neighborhood", wrong: ["tribe", "environment", "resident"] },
      { en: "admit", sentence: "I (   ) that I lost my father's favorite watch.", translation: "私は父のお気に入りの時計をなくしたことを認めた。", answer: "admitted", wrong: ["attempted", "prevented", "refused"] },
      { en: "generate", sentence: "Manager sold office building to (   ) income.", translation: "マネージャーは収入を生み出すためにオフィスビルを売却した。", answer: "generate", wrong: ["produce", "indicate", "gain"] },
      { en: "recommend", sentence: "Doctor (   ) that she eat more meat and eggs.", translation: "医者は彼女にもっと肉と卵を食べるよう勧めた。", answer: "recommended", wrong: ["recalled", "requested", "respected"] },
      { en: "demonstrate", sentence: "Book (   ) that education shapes society.", translation: "その本は教育が社会を形成すると示している。", answer: "demonstrates", wrong: ["determines", "trusts", "appreciates"] },
      { en: "presence", sentence: "(   ) of friends makes life more pleasant.", translation: "友人の存在は人生をより楽しくする。", answer: "Presence", wrong: ["Personality", "Principle", "Resource"] },
      { en: "advertise", sentence: "They (   ) their new computer games online.", translation: "彼らは新しいコンピューターゲームをオンラインで宣伝した。", answer: "advertise", wrong: ["adopt", "aid", "acquire"] },
      { en: "aid", sentence: "Many sent supplies to (   ) disaster victims.", translation: "多くの人が災害の被災者を援助するために物資を送った。", answer: "aid", wrong: ["address", "adopt", "add"] },
      { en: "bite", sentence: "Big dog (   ) my leg when I was a child.", translation: "子供の頃、大きな犬に足を噛まれた。", answer: "bit", wrong: ["consult", "invest", "quit"] },
      { en: "deliver", sentence: "He (   ) packages every day regardless of weather.", translation: "彼は天気に関係なく毎日荷物を配達する。", answer: "delivers", wrong: ["denies", "deals", "declares"] },
      { en: "locate", sentence: "Library is (   ) on the main street.", translation: "図書館はメインストリートに位置している。", answer: "located", wrong: ["appeared", "operated", "preferred"] },
    ]
  },
  {
    id: "source4",
    title: "B英単語ターゲット1900 小テスト④（451-500）",
    subtitle: "diversity, stock, occasion ...",
    words: [
      { en: "diversity", ja: "多様性；相違点", syl: "di·ver·si·ty", acc: 2 },
      { en: "stock", ja: "在庫品；蓄え；株" },
      { en: "occasion", ja: "場合，時；行事；機会", syl: "oc·ca·sion", acc: 2 },
      { en: "facility", ja: "施設，設備；機能；才能", syl: "fa·cil·i·ty", acc: 2 },
      { en: "lawyer", ja: "弁護士", syl: "law·yer", acc: 1 },
      { en: "philosophy", ja: "哲学；原理；人生観", syl: "phi·los·o·phy", acc: 2 },
      { en: "capital", ja: "資本；首都", syl: "cap·i·tal", acc: 1 },
      { en: "tribe", ja: "部族；仲間" },
      { en: "proper", ja: "適切な；正式の；主要な；固有の", syl: "prop·er", acc: 1 },
      { en: "conference", ja: "会議；協議", syl: "con·fer·ence", acc: 1 },
      { en: "annual", ja: "年1回の，例年の；1年間の", syl: "an·nu·al", acc: 1 },
      { en: "sufficient", ja: "十分な", syl: "suf·fi·cient", acc: 2 },
      { en: "contrary", ja: "反対の", syl: "con·trar·y", acc: 1 },
      { en: "crucial", ja: "重要な；決定的な", syl: "cru·cial", acc: 1 },
      { en: "somewhat", ja: "いくぶん，多少", syl: "some·what", acc: 1 },
      { en: "outcome", ja: "結果", syl: "out·come", acc: 1 },
      { en: "victim", ja: "犠牲（者）", syl: "vic·tim", acc: 1 },
      { en: "tip", ja: "助言；コツ；先端" },
      { en: "proportion", ja: "割合；比率", syl: "pro·por·tion", acc: 2 },
      { en: "humanity", ja: "人類；人間性", syl: "hu·man·i·ty", acc: 2 },
      { en: "dialect", ja: "方言", syl: "di·a·lect", acc: 1 },
      { en: "landscape", ja: "風景；景色", syl: "land·scape", acc: 1 },
      { en: "code", ja: "規範；暗号" },
      { en: "numerous", ja: "非常に数の多い", syl: "nu·mer·ous", acc: 1 },
      { en: "widespread", ja: "広範囲にわたる", syl: "wide·spread", acc: 1 },
      { en: "odd", ja: "奇妙な；奇数の" },
      { en: "multiple", ja: "多様な；複数の", syl: "mul·ti·ple", acc: 1 },
      { en: "superior", ja: "よりすぐれた", syl: "su·pe·ri·or", acc: 2 },
      { en: "virtual", ja: "仮想の；事実上の", syl: "vir·tu·al", acc: 1 },
      { en: "violent", ja: "（人・気質などが）激しい；暴力的な", syl: "vi·o·lent", acc: 1 },
      { en: "quantity", ja: "量；数量", syl: "quan·ti·ty", acc: 1 },
      { en: "unknown", ja: "未知の；知られていない", syl: "un·known", acc: 2 },
      { en: "substance", ja: "物質；実体", syl: "sub·stance", acc: 1 },
      { en: "regardless", ja: "かまわずに；…にかかわらず", syl: "re·gard·less", acc: 2 },
      { en: "narrow", ja: "狭い", syl: "nar·row", acc: 1 },
      { en: "notion", ja: "概念；考え", syl: "no·tion", acc: 1 },
      { en: "review", ja: "論評；批評；再検討", syl: "re·view", acc: 2 },
      { en: "organ", ja: "器官；臓器", syl: "or·gan", acc: 1 },
      { en: "mammal", ja: "哺乳動物", syl: "mam·mal", acc: 1 },
      { en: "stuff", ja: "私物；物；素材" },
      { en: "trait", ja: "特徴；特性" },
      { en: "norm", ja: "規範；標準" },
      { en: "trial", ja: "試験；裁判；試み", syl: "tri·al", acc: 1 },
      { en: "comfort", ja: "快適；慰め", syl: "com·fort", acc: 1 },
      { en: "linguistic", ja: "言語の；言語学の", syl: "lin·guis·tic", acc: 2 },
      { en: "civil", ja: "公民の；市民の；民間の", syl: "civ·il", acc: 1 },
      { en: "contemporary", ja: "現代の；同時代の", syl: "con·tem·po·rar·y", acc: 2 },
      { en: "strict", ja: "厳しい；厳格な" },
      { en: "immediate", ja: "即座の；直接の", syl: "im·me·di·ate", acc: 2 },
      { en: "sensitive", ja: "敏感な；繊細な", syl: "sen·si·tive", acc: 1 },
    ],
    cloze: [
      { en: "diversity", sentence: "Our company values cultural (   ) in the workplace.", translation: "私たちの会社は職場での文化的多様性を重視している。", answer: "diversity", wrong: ["majority", "priority", "quantity"] },
      { en: "stock", sentence: "The store has a large (   ) of winter clothes.", translation: "その店は冬服の在庫を大量に抱えている。", answer: "stock", wrong: ["crop", "trade", "habit"] },
      { en: "occasion", sentence: "She wore a beautiful dress for the special (   ).", translation: "彼女は特別な機会のために美しいドレスを着た。", answer: "occasion", wrong: ["option", "device", "minister"] },
      { en: "facility", sentence: "The new sports (   ) opened last month.", translation: "新しいスポーツ施設が先月オープンした。", answer: "facility", wrong: ["theory", "structure", "resident"] },
      { en: "lawyer", sentence: "He hired a (   ) to handle the contract.", translation: "彼は契約を扱うために弁護士を雇った。", answer: "lawyer", wrong: ["ancestor", "elite", "disaster"] },
      { en: "philosophy", sentence: "She studied Greek (   ) at university.", translation: "彼女は大学でギリシャ哲学を学んだ。", answer: "philosophy", wrong: ["technology", "literature", "theory"] },
      { en: "capital", sentence: "London is the (   ) of the United Kingdom.", translation: "ロンドンは英国の首都だ。", answer: "capital", wrong: ["profit", "wealth", "progress"] },
      { en: "tribe", sentence: "The (   ) has lived in the forest for centuries.", translation: "その部族は何世紀もその森で暮らしてきた。", answer: "tribe", wrong: ["species", "facility", "trait"] },
      { en: "proper", sentence: "Please wear (   ) clothes for the interview.", translation: "面接には適切な服装をしてください。", answer: "proper", wrong: ["fair", "overall", "ideal"] },
      { en: "conference", sentence: "The international (   ) will be held in Tokyo.", translation: "国際会議は東京で開催される。", answer: "conference", wrong: ["conflict", "consequence", "corporation"] },
      { en: "annual", sentence: "The company holds an (   ) meeting every spring.", translation: "その会社は毎春、年次総会を開く。", answer: "annual", wrong: ["novel", "actual", "elementary"] },
      { en: "sufficient", sentence: "We do not have (   ) time to finish the task.", translation: "その作業を終えるのに十分な時間がない。", answer: "sufficient", wrong: ["vast", "worth", "fundamental"] },
      { en: "contrary", sentence: "His opinion is (   ) to mine.", translation: "彼の意見は私の意見と反対だ。", answer: "contrary", wrong: ["cognitive", "contemporary", "relative"] },
      { en: "crucial", sentence: "Water is (   ) for all living things.", translation: "水はすべての生物にとって重要だ。", answer: "crucial", wrong: ["potential", "obvious", "numerous"] },
      { en: "somewhat", sentence: "The movie was (   ) disappointing.", translation: "その映画はいくぶん期待外れだった。", answer: "somewhat", wrong: ["moreover", "somehow", "anyway"] },
      { en: "outcome", sentence: "Nobody could predict the (   ) of the election.", translation: "誰も選挙の結果を予測できなかった。", answer: "outcome", wrong: ["topic", "concept", "feature"] },
      { en: "victim", sentence: "The (   ) of the accident was taken to hospital.", translation: "その事故の犠牲者は病院に運ばれた。", answer: "victim", wrong: ["vehicle", "threat", "resident"] },
      { en: "tip", sentence: "Let me give you a useful (   ) for the exam.", translation: "試験に役立つ助言をあげよう。", answer: "tip", wrong: ["nail", "trap", "hole"] },
      { en: "proportion", sentence: "A large (   ) of students passed the test.", translation: "大きな割合の学生が試験に合格した。", answer: "proportion", wrong: ["feature", "profit", "range"] },
      { en: "humanity", sentence: "War threatens the future of all (   ).", translation: "戦争は全人類の未来を脅かす。", answer: "humanity", wrong: ["memory", "hypothesis", "occasion"] },
      { en: "dialect", sentence: "People in this region speak a local (   ).", translation: "この地域の人々は地元の方言を話す。", answer: "dialect", wrong: ["detail", "feature", "content"] },
      { en: "landscape", sentence: "The painting shows a beautiful winter (   ).", translation: "その絵は美しい冬の風景を描いている。", answer: "landscape", wrong: ["district", "habitat", "territory"] },
      { en: "code", sentence: "Engineers follow a strict safety (   ).", translation: "技術者は厳しい安全規範に従う。", answer: "code", wrong: ["trend", "issue", "agreement"] },
      { en: "numerous", sentence: "She has received (   ) awards for her research.", translation: "彼女は研究で非常に数多くの賞を受けている。", answer: "numerous", wrong: ["vast", "conscious", "huge"] },
      { en: "widespread", sentence: "The disease became (   ) within weeks.", translation: "その病気は数週間で広範囲に広がった。", answer: "widespread", wrong: ["thick", "overall", "domestic"] },
      { en: "odd", sentence: "There was something (   ) about his behavior.", translation: "彼の行動には何か奇妙なところがあった。", answer: "odd", wrong: ["extreme", "negative", "initial"] },
      { en: "multiple", sentence: "There are (   ) reasons for the change.", translation: "その変化には複数の理由がある。", answer: "multiple", wrong: ["crucial", "constant", "marine"] },
      { en: "superior", sentence: "This model is (   ) to the older one.", translation: "このモデルは旧型よりすぐれている。", answer: "superior", wrong: ["ancient", "various", "tiny"] },
      { en: "virtual", sentence: "Students attended a (   ) class online.", translation: "学生はオンラインで仮想授業に出席した。", answer: "virtual", wrong: ["ordinary", "false", "verbal"] },
      { en: "violent", sentence: "The film contains many (   ) scenes.", translation: "その映画には多くの激しい場面が含まれる。", answer: "violent", wrong: ["current", "brilliant", "direct"] },
      { en: "quantity", sentence: "A small (   ) of salt improves the flavor.", translation: "少量の塩が風味を良くする。", answer: "quantity", wrong: ["quality", "majority", "priority"] },
      { en: "unknown", sentence: "The cause of the fire is still (   ).", translation: "火事の原因はまだ未知だ。", answer: "unknown", wrong: ["aware", "obvious", "narrow"] },
      { en: "substance", sentence: "Water is a (   ) made of hydrogen and oxygen.", translation: "水は水素と酸素からできた物質だ。", answer: "substance", wrong: ["surface", "structure", "quantity"] },
      { en: "regardless", sentence: "She continued working (   ) of the noise.", translation: "彼女は騒音にかまわず働き続けた。", answer: "regardless", wrong: ["instead", "aside", "apart"] },
      { en: "narrow", sentence: "The car could not pass through the (   ) street.", translation: "車はその狭い通りを通れなかった。", answer: "narrow", wrong: ["broad", "steep", "plain"] },
      { en: "notion", sentence: "He considers the (   ) of peace as the absence of war.", translation: "彼は平和の概念を戦争のない状態としてとらえている。", answer: "notion", wrong: ["statistic", "code", "interest"] },
      { en: "review", sentence: "I read his (   ) of the newly published book.", translation: "私はその新刊書についての彼の論評を読んだ。", answer: "review", wrong: ["literature", "analysis", "perspective"] },
      { en: "organ", sentence: "The brain is the most advanced (   ) in the known universe.", translation: "脳は既知の宇宙において最も進歩した器官である。", answer: "organ", wrong: ["cell", "content", "structure"] },
      { en: "mammal", sentence: "Most (   ) including human beings can maintain their body temperature naturally.", translation: "人間を含むたいていの哺乳動物は自然に体温を保つことができる。", answer: "mammals", wrong: ["materials", "manners", "masses"] },
      { en: "stuff", sentence: "She keeps her personal (   ) in the cabinet in her office.", translation: "彼女は事務所の戸棚の中に私物を保管している。", answer: "stuff", wrong: ["substance", "skill", "range"] },
      { en: "trait", sentence: "She bears physical (   ) common to the general Japanese population.", translation: "彼女は一般的日本人に共通する身体的特徴を備えている。", answer: "traits", wrong: ["trends", "status", "trades"] },
      { en: "norm", sentence: "You are expected to adapt to changes in social (   ).", translation: "社会規範の変化に順応することが求められている。", answer: "norms", wrong: ["practices", "aspects", "rights"] },
      { en: "trial", sentence: "Singapore has started the world's first public (   ) of the robo-taxi service.", translation: "シンガポールはロボットタクシー運行業務の世界初の公開試験を始めた。", answer: "trial", wrong: ["trick", "merit", "territory"] },
      { en: "comfort", sentence: "He has been living in (   ) and safety since his retirement.", translation: "彼は引退以来ずっと快適で安全に暮らしている。", answer: "comfort", wrong: ["emotion", "reward", "conference"] },
      { en: "linguistic", sentence: "Translators apply their general and (   ) knowledge.", translation: "翻訳者は自らの一般知識と言語の知識を用いる。", answer: "linguistic", wrong: ["legal", "academic", "genetic"] },
      { en: "civil", sentence: "The U.S. Supreme Court often makes decisions concerning (   ) rights.", translation: "合衆国最高裁判所はしばしば公民権にかかわる判断を下す。", answer: "civil", wrong: ["social", "rural", "legal"] },
      { en: "contemporary", sentence: "If you prefer (   ) art, you should visit Tate Modern.", translation: "現代美術が好みなら，テートモダン美術館を訪れるべきだ。", answer: "contemporary", wrong: ["common", "domestic", "ordinary"] },
      { en: "strict", sentence: "Australia has taken (   ) measures against illegal imports.", translation: "オーストラリアは不正輸入に対して厳しい対策をとってきた。", answer: "strict", wrong: ["fair", "accurate", "plastic"] },
      { en: "immediate", sentence: "He gave us an (   ) answer on the matter.", translation: "彼は私たちにその問題に関して即答した。", answer: "immediate", wrong: ["constant", "efficient", "recent"] },
      { en: "sensitive", sentence: "My teeth are extremely (   ) to cold things.", translation: "私の歯は冷たい物に極めて敏感である。", answer: "sensitive", wrong: ["patient", "specific", "relative"] },
    ]
  },
  {
    id: "source5",
    title: "B英単語ターゲット1900 小テスト⑤（501-550）",
    subtitle: "overcome, request, hate ...",
    words: [
      { en: "overcome", ja: "を克服する", syl: "o·ver·come", acc: 3 },
      { en: "request", ja: "に頼む；を要請する", syl: "re·quest", acc: 2 },
      { en: "hate", ja: "をひどく嫌う；を残念に思う" },
      { en: "ensure", ja: "を確実にする；を守る", syl: "en·sure", acc: 2 },
      { en: "oppose", ja: "に反対する；を対抗させる", syl: "op·pose", acc: 2 },
      { en: "credit", ja: "（功績など）を帰する；を信じる；信用", syl: "cred·it", acc: 1 },
      { en: "beat", ja: "を打ち負かす；（を）打つ，たたく" },
      { en: "arise", ja: "生じる", syl: "a·rise", acc: 2 },
      { en: "rush", ja: "急いで行く；性急に行動する；をせき立てる" },
      { en: "fascinate", ja: "を魅了する", syl: "fas·ci·nate", acc: 1 },
      { en: "celebrate", ja: "を祝う；を挙行する", syl: "cel·e·brate", acc: 1 },
      { en: "cure", ja: "を治す；を取り除く；（病気が）治る" },
      { en: "regret", ja: "を後悔する", syl: "re·gret", acc: 2 },
      { en: "budget", ja: "予算；経費", syl: "budg·et", acc: 1 },
      { en: "debt", ja: "借金，負債；恩義" },
      { en: "concentrate", ja: "を集中する", syl: "con·cen·trate", acc: 1 },
      { en: "interpret", ja: "を解釈する", syl: "in·ter·pret", acc: 2 },
      { en: "obtain", ja: "を得る", syl: "ob·tain", acc: 2 },
      { en: "announce", ja: "を発表［公表］する", syl: "an·nounce", acc: 2 },
      { en: "freeze", ja: "凍る" },
      { en: "employ", ja: "を雇う", syl: "em·ploy", acc: 2 },
      { en: "disappoint", ja: "を失望させる", syl: "dis·ap·point", acc: 3 },
      { en: "absorb", ja: "を吸収する", syl: "ab·sorb", acc: 2 },
      { en: "ban", ja: "を（法的に）禁止する" },
      { en: "blame", ja: "を責める" },
      { en: "interact", ja: "影響し合う", syl: "in·ter·act", acc: 3 },
      { en: "insight", ja: "見識；洞察", syl: "in·sight", acc: 1 },
      { en: "alter", ja: "を変える", syl: "al·ter", acc: 1 },
      { en: "adjust", ja: "を調整する", syl: "ad·just", acc: 2 },
      { en: "innovation", ja: "革新", syl: "in·no·va·tion", acc: 3 },
      { en: "transform", ja: "を変形させる；を変える", syl: "trans·form", acc: 2 },
      { en: "manufacture", ja: "を製造する", syl: "man·u·fac·ture", acc: 3 },
      { en: "arrange", ja: "を手配する；を整える", syl: "ar·range", acc: 2 },
      { en: "transport", ja: "を輸送する", syl: "trans·port", acc: 2 },
      { en: "recover", ja: "回復する；を取り戻す", syl: "re·cov·er", acc: 2 },
      { en: "translate", ja: "を翻訳する", syl: "trans·late", acc: 2 },
      { en: "emphasize", ja: "を強調する", syl: "em·pha·size", acc: 1 },
      { en: "inform", ja: "に知らせる", syl: "in·form", acc: 2 },
      { en: "grant", ja: "を与える；を認める" },
      { en: "construct", ja: "を建設する", syl: "con·struct", acc: 2 },
      { en: "differ", ja: "異なる", syl: "dif·fer", acc: 1 },
      { en: "criticize", ja: "を批判する", syl: "crit·i·cize", acc: 1 },
      { en: "hang", ja: "を掛ける；を吊るす" },
      { en: "fee", ja: "料金；入館料" },
      { en: "expense", ja: "経費；費用", syl: "ex·pense", acc: 2 },
      { en: "confirm", ja: "を確認する", syl: "con·firm", acc: 2 },
      { en: "loan", ja: "貸付金" },
      { en: "alarm", ja: "不安；警報", syl: "a·larm", acc: 2 },
      { en: "duty", ja: "義務；任務", syl: "du·ty", acc: 1 },
      { en: "emergency", ja: "緊急（事態）", syl: "e·mer·gen·cy", acc: 2 },
    ],
    cloze: [
      { en: "overcome", sentence: "She worked hard to (   ) her fear of speaking in public.", translation: "彼女は人前で話す恐怖を克服しようと懸命に努力した。", answer: "overcome", wrong: ["offer", "operate", "organize"] },
      { en: "request", sentence: "Passengers may (   ) a special meal in advance.", translation: "乗客は事前に特別食を頼むことができる。", answer: "request", wrong: ["reduce", "reflect", "recall"] },
      { en: "hate", sentence: "Many children (   ) doing homework on weekends.", translation: "多くの子供は週末に宿題をするのをひどく嫌う。", answer: "hate", wrong: ["hide", "settle", "handle"] },
      { en: "ensure", sentence: "We must (   ) the safety of all visitors.", translation: "すべての訪問者の安全を確実にしなければならない。", answer: "ensure", wrong: ["encounter", "earn", "expose"] },
      { en: "oppose", sentence: "Many residents (   ) the new construction plan.", translation: "多くの住民は新しい建設計画に反対している。", answer: "oppose", wrong: ["suppose", "offer", "observe"] },
      { en: "credit", sentence: "He took all the (   ) for the team's success.", translation: "彼はチームの成功の功績を独り占めした。", answer: "credit", wrong: ["challenge", "claim", "criticism"] },
      { en: "beat", sentence: "Our team managed to (   ) the champions yesterday.", translation: "私たちのチームは昨日、王者を打ち負かすことができた。", answer: "beat", wrong: ["ban", "admit", "bear"] },
      { en: "arise", sentence: "Problems often (   ) when people do not communicate.", translation: "人々が意思疎通しないと問題がよく生じる。", answer: "arise", wrong: ["adapt", "appeal", "advance"] },
      { en: "rush", sentence: "Don't (   ) your decision; think carefully.", translation: "決断を急ぐな、よく考えなさい。", answer: "rush", wrong: ["search", "suffer", "exist"] },
      { en: "fascinate", sentence: "Magic tricks always (   ) young children.", translation: "手品はいつも幼い子供を魅了する。", answer: "fascinate", wrong: ["gain", "demonstrate", "appreciate"] },
      { en: "celebrate", sentence: "They gathered to (   ) her birthday.", translation: "彼らは彼女の誕生日を祝うために集まった。", answer: "celebrate", wrong: ["claim", "combine", "compare"] },
      { en: "cure", sentence: "This medicine can (   ) the disease completely.", translation: "この薬はその病気を完全に治すことができる。", answer: "cure", wrong: ["convince", "connect", "criticize"] },
      { en: "regret", sentence: "You will (   ) it if you give up now.", translation: "今あきらめたら後悔するよ。", answer: "regret", wrong: ["refuse", "regard", "reject"] },
      { en: "budget", sentence: "The family planned a monthly (   ) for food.", translation: "その家族は食費の月間予算を立てた。", answer: "budget", wrong: ["capital", "benefit", "achievement"] },
      { en: "debt", sentence: "He worked two jobs to pay off his (   ).", translation: "彼は借金を返すために二つの仕事をした。", answer: "debt", wrong: ["degree", "budget", "bias"] },
      { en: "concentrate", sentence: "It is hard to (   ) in a noisy room.", translation: "騒がしい部屋で集中するのは難しい。", answer: "concentrate", wrong: ["complete", "complain", "compete"] },
      { en: "interpret", sentence: "It is difficult to (   ) his silence.", translation: "彼の沈黙を解釈するのは難しい。", answer: "interpret", wrong: ["intend", "injure", "investigate"] },
      { en: "obtain", sentence: "You can (   ) a visa at the embassy.", translation: "大使館でビザを得ることができる。", answer: "obtain", wrong: ["offer", "operate", "maintain"] },
      { en: "announce", sentence: "The company will (   ) its results tomorrow.", translation: "その会社は明日、業績を発表する。", answer: "announce", wrong: ["expose", "pronounce", "review"] },
      { en: "freeze", sentence: "Water will (   ) at zero degrees.", translation: "水は0度で凍る。", answer: "freeze", wrong: ["rely", "search", "occur"] },
      { en: "employ", sentence: "The factory plans to (   ) more workers.", translation: "その工場はより多くの労働者を雇う計画だ。", answer: "employ", wrong: ["educate", "emphasize", "earn"] },
      { en: "disappoint", sentence: "I don't want to (   ) my parents.", translation: "両親を失望させたくない。", answer: "disappoint", wrong: ["determine", "destroy", "distinguish"] },
      { en: "absorb", sentence: "Plants (   ) water through their roots.", translation: "植物は根から水を吸収する。", answer: "absorb", wrong: ["obtain", "adopt", "add"] },
      { en: "ban", sentence: "The city decided to (   ) smoking in parks.", translation: "市は公園での喫煙を禁止することにした。", answer: "ban", wrong: ["blame", "compare", "bear"] },
      { en: "blame", sentence: "Don't (   ) others for your own mistakes.", translation: "自分の失敗を他人のせいにするな。", answer: "blame", wrong: ["compare", "bear", "assume"] },
      { en: "interact", sentence: "Children learn how to (   ) with others at school.", translation: "子供たちは学校で他者と影響し合う方法を学ぶ。", answer: "interact", wrong: ["behave", "increase", "adapt"] },
      { en: "insight", sentence: "Her book gives a deep (   ) into human nature.", translation: "彼女の本は人間の本質への深い見識を与える。", answer: "insight", wrong: ["choice", "strategy", "discipline"] },
      { en: "alter", sentence: "We had to (   ) our plans because of the rain.", translation: "雨のため計画を変えなければならなかった。", answer: "alter", wrong: ["allow", "attract", "attempt"] },
      { en: "adjust", sentence: "You can (   ) the height of the chair.", translation: "椅子の高さを調整できる。", answer: "adjust", wrong: ["adopt", "advertise", "aid"] },
      { en: "innovation", sentence: "Technological (   ) has changed our daily lives.", translation: "技術革新は私たちの日常生活を変えた。", answer: "innovation", wrong: ["progress", "weapon", "struggle"] },
      { en: "transform", sentence: "The internet has (   ) the way we communicate.", translation: "インターネットは私たちの意思疎通の方法を変えた。", answer: "transformed", wrong: ["transported", "translated", "tore"] },
      { en: "manufacture", sentence: "The company (   ) cars in three countries.", translation: "その会社は3か国で車を製造している。", answer: "manufactures", wrong: ["maintains", "manages", "measures"] },
      { en: "arrange", sentence: "She will (   ) a meeting for next week.", translation: "彼女は来週の会議を手配する。", answer: "arrange", wrong: ["arrive", "arise", "assist"] },
      { en: "transport", sentence: "Trucks (   ) goods across the country.", translation: "トラックが国中に商品を輸送する。", answer: "transport", wrong: ["transform", "translate", "trade"] },
      { en: "recover", sentence: "It took him a month to (   ) from the illness.", translation: "彼が病気から回復するのに1か月かかった。", answer: "recover", wrong: ["remove", "reduce", "recall"] },
      { en: "translate", sentence: "She (   ) an English essay into French with ease.", translation: "彼女は英語のエッセイを容易にフランス語に翻訳した。", answer: "translated", wrong: ["transported", "transformed", "tore"] },
      { en: "emphasize", sentence: "Ecologists are (   ) the need to protect the environment.", translation: "生態学者は自然環境を保護する必要性を強調している。", answer: "emphasizing", wrong: ["expecting", "establishing", "educating"] },
      { en: "inform", sentence: "Please (   ) us of any change in your plan.", translation: "計画のどんな変更も我々にお知らせください。", answer: "inform", wrong: ["approach", "mention", "embarrass"] },
      { en: "grant", sentence: "A fingerprint scanner can be used to (   ) employees access to certain areas.", translation: "指紋スキャナーは社員にある区域への立ち入り権を与えるのに使うことができる。", answer: "grant", wrong: ["bother", "disappoint", "guarantee"] },
      { en: "construct", sentence: "The city plans to (   ) new public transportation facilities.", translation: "市は新しい公共輸送施設を建設する計画である。", answer: "construct", wrong: ["connect", "confuse", "confirm"] },
      { en: "differ", sentence: "Humans (   ) from other animals mostly due to their large brains.", translation: "人間は主としてその大きな脳のためにほかの動物と異なる。", answer: "differ", wrong: ["decrease", "decline", "depend"] },
      { en: "criticize", sentence: "Employees (   ) the company president for poor management.", translation: "従業員たちは下手な経営を理由に社長を批判した。", answer: "criticized", wrong: ["compared", "organized", "selected"] },
      { en: "hang", sentence: "He (   ) his jacket on the back of his chair.", translation: "彼は椅子の背に自分の上着を掛けた。", answer: "hung", wrong: ["hid", "dragged", "raised"] },
      { en: "fee", sentence: "On weekends, the City Museum reduces the entrance (   ) for children.", translation: "週末に，市博物館は子供の入館料を下げる。", answer: "fee", wrong: ["capital", "welfare", "expense"] },
      { en: "expense", sentence: "The manager aims to cut down personnel (   ).", translation: "その経営者は人件費を削減しようとしている。", answer: "expenses", wrong: ["profits", "fines", "figures"] },
      { en: "confirm", sentence: "The postal worker (   ) my identity before handing me the express letter.", translation: "その郵便局員は速達の手紙を私に渡す前に私の身元を確認した。", answer: "confirmed", wrong: ["complicated", "completed", "conducted"] },
      { en: "loan", sentence: "He spent ten years paying back the bank (   ).", translation: "彼は銀行の貸付金を返済するのに10年を費やした。", answer: "loan", wrong: ["expense", "profit", "insurance"] },
      { en: "alarm", sentence: "When she heard a strange sound, she looked around in (   ).", translation: "彼女は奇妙な物音を聞いたとき，不安を感じて辺りを見回した。", answer: "alarm", wrong: ["account", "content", "aim"] },
      { en: "duty", sentence: "He was blamed for not doing his (   ) as a parent.", translation: "彼は親としての義務を果たさないことで責められた。", answer: "duty", wrong: ["detail", "fault", "facility"] },
      { en: "emergency", sentence: "You need to know what to do in an (   ).", translation: "君は緊急の場合にどうすべきかを知っておく必要がある。", answer: "emergency", wrong: ["industry", "hypothesis", "strategy"] },
    ]
  },
  {
    id: "source6",
    title: "B英単語ターゲット1900 小テスト⑥（551-600）",
    subtitle: "immigration, route, barrier ...",
    words: [
      { en: "immigration", ja: "（他国からの）移民，移住；入国管理", syl: "im·mi·gra·tion", acc: 3 },
      { en: "route", ja: "道（筋）；路線；手段" },
      { en: "barrier", ja: "障壁；防壁", syl: "bar·ri·er", acc: 1 },
      { en: "colony", ja: "植民地；集団居住地", syl: "col·o·ny", acc: 1 },
      { en: "routine", ja: "決まり切った仕事；いつもの手順", syl: "rou·tine", acc: 2 },
      { en: "grain", ja: "穀物；粒；きめ" },
      { en: "contract", ja: "契約（書）；協定", syl: "con·tract", acc: 1 },
      { en: "dramatic", ja: "劇的な；演劇の", syl: "dra·mat·ic", acc: 2 },
      { en: "welfare", ja: "福祉，幸福", syl: "wel·fare", acc: 1 },
      { en: "abstract", ja: "抽象的な", syl: "ab·stract", acc: 1 },
      { en: "distinct", ja: "明らかに異なる；明瞭な", syl: "dis·tinct", acc: 2 },
      { en: "anxious", ja: "心配して；切望して", syl: "anx·ious", acc: 1 },
      { en: "brief", ja: "簡潔な；短い" },
      { en: "prime", ja: "主要な，最も重要な；最適な；極上の" },
      { en: "exact", ja: "正確な；まさにその", syl: "ex·act", acc: 2 },
      { en: "candidate", ja: "候補（者）", syl: "can·di·date", acc: 1 },
      { en: "stereotype", ja: "固定観念", syl: "ster·e·o·type", acc: 1 },
      { en: "corporation", ja: "（大）企業", syl: "cor·po·ra·tion", acc: 3 },
      { en: "mood", ja: "気分" },
      { en: "statistics", ja: "統計", syl: "sta·tis·tics", acc: 2 },
      { en: "physician", ja: "医師", syl: "phy·si·cian", acc: 2 },
      { en: "hypothesis", ja: "仮説", syl: "hy·poth·e·sis", acc: 2 },
      { en: "vital", ja: "必要不可欠な；生命の", syl: "vi·tal", acc: 1 },
      { en: "extraordinary", ja: "並はずれた", syl: "ex·traor·di·nar·y", acc: 2 },
      { en: "minor", ja: "重要でない；小さい", syl: "mi·nor", acc: 1 },
      { en: "alien", ja: "異質の；外国の", syl: "al·ien", acc: 1 },
      { en: "stable", ja: "安定した", syl: "sta·ble", acc: 1 },
      { en: "ethnic", ja: "民族の", syl: "eth·nic", acc: 1 },
      { en: "latter", ja: "後者の", syl: "lat·ter", acc: 1 },
      { en: "precise", ja: "正確な", syl: "pre·cise", acc: 2 },
      { en: "disorder", ja: "障害；無秩序", syl: "dis·or·der", acc: 2 },
      { en: "unexpected", ja: "予期しない", syl: "un·ex·pect·ed", acc: 3 },
      { en: "discipline", ja: "規律；訓練", syl: "dis·ci·pline", acc: 1 },
      { en: "flexible", ja: "柔軟な", syl: "flex·i·ble", acc: 1 },
      { en: "weapon", ja: "武器", syl: "weap·on", acc: 1 },
      { en: "minister", ja: "大臣；牧師", syl: "min·is·ter", acc: 1 },
      { en: "depression", ja: "憂うつ；不況；くぼみ", syl: "de·pres·sion", acc: 2 },
      { en: "democracy", ja: "民主主義", syl: "de·moc·ra·cy", acc: 2 },
      { en: "disadvantage", ja: "不利（な点）", syl: "dis·ad·van·tage", acc: 3 },
      { en: "myth", ja: "作り話；神話" },
      { en: "client", ja: "顧客；依頼人", syl: "cli·ent", acc: 1 },
      { en: "fellow", ja: "仲間；同僚", syl: "fel·low", acc: 1 },
      { en: "ingredient", ja: "材料；成分；要素", syl: "in·gre·di·ent", acc: 2 },
      { en: "motion", ja: "動き；運動；可動域", syl: "mo·tion", acc: 1 },
      { en: "curious", ja: "好奇心が強い；奇妙な", syl: "cu·ri·ous", acc: 1 },
      { en: "aggressive", ja: "攻撃的な；積極的な", syl: "ag·gres·sive", acc: 2 },
      { en: "conventional", ja: "従来の；従来型の；慣習的な", syl: "con·ven·tion·al", acc: 2 },
      { en: "treasure", ja: "宝；財宝；国宝", syl: "treas·ure", acc: 1 },
      { en: "visible", ja: "目に見える", syl: "vis·i·ble", acc: 1 },
      { en: "initial", ja: "初期の；最初の", syl: "i·ni·tial", acc: 2 },
    ],
    cloze: [
      { en: "immigration", sentence: "The government tightened its (   ) policy last year.", translation: "政府は昨年、移民政策を強化した。", answer: "immigration", wrong: ["imagination", "colony", "habitat"] },
      { en: "route", sentence: "We took the shortest (   ) to the station.", translation: "私たちは駅まで最短の道を通った。", answer: "route", wrong: ["peril", "measure", "routine"] },
      { en: "barrier", sentence: "Language can be a (   ) to communication.", translation: "言語は意思疎通の障壁になり得る。", answer: "barrier", wrong: ["struggle", "fine", "threat"] },
      { en: "colony", sentence: "The country once ruled a large overseas (   ).", translation: "その国はかつて大きな海外の植民地を支配していた。", answer: "colony", wrong: ["territory", "region", "habitat"] },
      { en: "routine", sentence: "Brushing your teeth is part of your daily (   ).", translation: "歯磨きは日々の決まった習慣の一部だ。", answer: "routine", wrong: ["ritual", "progress", "instrument"] },
      { en: "grain", sentence: "Rice is an important (   ) in many countries.", translation: "米は多くの国で重要な穀物だ。", answer: "grain", wrong: ["tissue", "harvest", "clay"] },
      { en: "contract", sentence: "Both sides signed the (   ) yesterday.", translation: "双方は昨日、契約書に署名した。", answer: "contract", wrong: ["document", "contrast", "content"] },
      { en: "dramatic", sentence: "The team made a (   ) comeback in the final minute.", translation: "そのチームは最後の1分で劇的な逆転をした。", answer: "dramatic", wrong: ["exotic", "lunatic", "pessimistic"] },
      { en: "welfare", sentence: "The government spends a lot on social (   ).", translation: "政府は社会福祉に多くを支出する。", answer: "welfare", wrong: ["wisdom", "wealth", "therapy"] },
      { en: "abstract", sentence: "Modern art is often too (   ) for me to understand.", translation: "現代美術はしばしば抽象的すぎて私には理解できない。", answer: "abstract", wrong: ["ethnic", "exact", "potential"] },
      { en: "distinct", sentence: "There is a (   ) difference between the two species.", translation: "その2種の間には明らかに異なる違いがある。", answer: "distinct", wrong: ["appropriate", "direct", "obvious"] },
      { en: "anxious", sentence: "She felt (   ) about the test results.", translation: "彼女は試験の結果を心配していた。", answer: "anxious", wrong: ["conscious", "enormous", "certain"] },
      { en: "brief", sentence: "He gave a (   ) summary of the report.", translation: "彼は報告書の簡潔な要約を述べた。", answer: "brief", wrong: ["distant", "thick", "minor"] },
      { en: "prime", sentence: "Health is of (   ) importance in your life.", translation: "健康は人生で最も重要だ。", answer: "prime", wrong: ["artistic", "distinct", "proper"] },
      { en: "exact", sentence: "Can you tell me the (   ) time?", translation: "正確な時刻を教えてくれますか。", answer: "exact", wrong: ["evil", "strict", "extreme"] },
      { en: "candidate", sentence: "She is the best (   ) for the job.", translation: "彼女はその仕事の最適な候補者だ。", answer: "candidate", wrong: ["companion", "opponent", "minister"] },
      { en: "stereotype", sentence: "We should avoid judging people by (   ).", translation: "固定観念で人を判断するのは避けるべきだ。", answer: "stereotype", wrong: ["structure", "concept", "mindset"] },
      { en: "corporation", sentence: "He works for a large international (   ).", translation: "彼は大きな国際企業で働いている。", answer: "corporation", wrong: ["consequence", "income", "trade"] },
      { en: "mood", sentence: "Good music can improve your (   ).", translation: "よい音楽は気分を良くする。", answer: "mood", wrong: ["reputation", "passion", "courage"] },
      { en: "statistics", sentence: "The (   ) show a rise in population.", translation: "統計は人口の増加を示している。", answer: "statistics", wrong: ["features", "institutions", "authorities"] },
      { en: "physician", sentence: "The (   ) advised him to rest for a week.", translation: "医師は彼に1週間休むよう助言した。", answer: "physician", wrong: ["author", "minister", "secretary"] },
      { en: "hypothesis", sentence: "The experiment supported her (   ).", translation: "その実験は彼女の仮説を裏付けた。", answer: "hypothesis", wrong: ["perspective", "claim", "concept"] },
      { en: "vital", sentence: "Sleep is (   ) for good health.", translation: "睡眠は健康に必要不可欠だ。", answer: "vital", wrong: ["appropriate", "odd", "sufficient"] },
      { en: "extraordinary", sentence: "She has an (   ) talent for music.", translation: "彼女は音楽に並はずれた才能がある。", answer: "extraordinary", wrong: ["negative", "modern", "rude"] },
      { en: "minor", sentence: "He made only a (   ) mistake.", translation: "彼はわずかな（重要でない）間違いをしただけだ。", answer: "minor", wrong: ["huge", "valuable", "unique"] },
      { en: "alien", sentence: "The custom felt completely (   ) to the visitors.", translation: "その慣習は訪問者にはまったく異質に感じられた。", answer: "alien", wrong: ["familiar", "equal", "irrelevant"] },
      { en: "stable", sentence: "The patient's condition is now (   ).", translation: "患者の状態は今は安定している。", answer: "stable", wrong: ["equal", "obvious", "reluctant"] },
      { en: "ethnic", sentence: "The festival celebrates many (   ) cultures.", translation: "その祭りは多くの民族文化を祝う。", answer: "ethnic", wrong: ["domestic", "verbal", "artistic"] },
      { en: "latter", sentence: "Of the two plans, I prefer the (   ).", translation: "二つの計画のうち、私は後者を好む。", answer: "latter", wrong: ["minor", "private", "verbal"] },
      { en: "precise", sentence: "Engineers need (   ) measurements.", translation: "技術者は正確な測定を必要とする。", answer: "precise", wrong: ["specific", "strict", "crucial"] },
      { en: "disorder", sentence: "The doctor diagnosed a sleep (   ).", translation: "医師は睡眠障害と診断した。", answer: "disorder", wrong: ["disaster", "decline", "display"] },
      { en: "unexpected", sentence: "His visit was completely (   ).", translation: "彼の訪問はまったく予期しないものだった。", answer: "unexpected", wrong: ["unknown", "uncertain", "unlimited"] },
      { en: "discipline", sentence: "Soldiers are trained with strict (   ).", translation: "兵士は厳しい規律で訓練される。", answer: "discipline", wrong: ["disorder", "decline", "division"] },
      { en: "flexible", sentence: "Our schedule is quite (   ).", translation: "私たちの予定はかなり柔軟だ。", answer: "flexible", wrong: ["fragile", "formal", "fertile"] },
      { en: "weapon", sentence: "The police found a dangerous (   ) at the scene.", translation: "警察は現場で危険な武器を発見した。", answer: "weapon", wrong: ["wagon", "wealth", "witness"] },
      { en: "minister", sentence: "The Prime (   )'s explanations were sometimes inconsistent.", translation: "総理大臣の説明はときに首尾一貫していなかった。", answer: "Minister", wrong: ["Material", "Glacier", "Institution"] },
      { en: "depression", sentence: "Experts say that aerobic exercise reduces stress and (   ).", translation: "専門家は有酸素運動がストレスや憂うつを軽減すると言う。", answer: "depression", wrong: ["degree", "occasion", "fault"] },
      { en: "democracy", sentence: "Majority rule is the basic principle of (   ).", translation: "多数決原理は民主主義の基本原則である。", answer: "democracy", wrong: ["autonomy", "aristocracy", "folklore"] },
      { en: "disadvantage", sentence: "Poor children tend to suffer educational and social (   ).", translation: "貧しい子供たちは教育的・社会的不利を被る傾向がある。", answer: "disadvantages", wrong: ["discoveries", "endeavors", "avoidances"] },
      { en: "myth", sentence: "It is a total (   ) that men are better drivers than women.", translation: "男性が女性より車の運転が上手であるというのはまったくの作り話である。", answer: "myth", wrong: ["hypothesis", "literature", "imagination"] },
      { en: "client", sentence: "She had a business meeting with an important (   ).", translation: "彼女は重要な顧客との商談を持った。", answer: "client", wrong: ["resident", "colleague", "clay"] },
      { en: "fellow", sentence: "You should get along with your (   ) at work.", translation: "職場の同僚とうまくやっていくべきである。", answer: "fellows", wrong: ["vocations", "sorrows", "spouses"] },
      { en: "ingredient", sentence: "He wanted to know the calories and the (   ) of the dish.", translation: "彼はその料理のカロリーと材料を知りたがった。", answer: "ingredients", wrong: ["glaciers", "individuals", "contents"] },
      { en: "motion", sentence: "Exercise may improve your body's range of (   ).", translation: "運動は身体の可動域を改善し得る。", answer: "motion", wrong: ["removal", "passage", "motive"] },
      { en: "curious", sentence: "Students should be (   ) about the world around them.", translation: "学生は自分の周りの世界に関して好奇心旺盛であるべきだ。", answer: "curious", wrong: ["anxious", "numerous", "patient"] },
      { en: "aggressive", sentence: "She has an (   ) attitude to her junior colleagues.", translation: "彼女は職場の後輩に対し攻撃的な態度をとる。", answer: "aggressive", wrong: ["cognitive", "active", "private"] },
      { en: "conventional", sentence: "This product is far superior to (   ) models.", translation: "この製品は従来型よりはるかにすぐれている。", answer: "conventional", wrong: ["common", "chemical", "political"] },
      { en: "treasure", sentence: "The painting of Christ in the museum is a national (   ).", translation: "その美術館にあるキリストの絵画は国宝である。", answer: "treasure", wrong: ["material", "priority", "harvest"] },
      { en: "visible", sentence: "The shampoo had a clearly (   ) effect on her hair.", translation: "そのシャンプーは彼女の髪の毛にはっきりと目に見える効果があった。", answer: "visible", wrong: ["permanent", "precise", "vital"] },
      { en: "initial", sentence: "(   ) treatment is crucial for those with breast cancer.", translation: "初期の治療が乳癌にかかった人にとって重大である。", answer: "Initial", wrong: ["Principal", "Remote", "Social"] },
    ]
  }
];
